# -*- coding: utf-8 -*-
"""PS1.jl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ByIt6kOdBkmRTfX-ub3GlMJ4lX7NyPm

Problem 2
"""

using Plots

num = 100

function VFI(beta, A, alpha, delta)
tol = 1e-7
maxiter = 10000

# force parameters to be in the sets given
@assert 0 < beta < 1; @assert A > 0; @assert 0 < alpha < 1; @assert 0 < delta <= 1

timer = time() # determine runtime

# Initialize all variables outside of loop #
# k-grid where the last element is 10
kgrid = range(0,10, length = num)

# let v be a vector of zeroes
V = zeros(num)
V[1] = -100
Vj = copy(V) # use copy so Vj does not change with V

n_optimal = ones(Int,num)
dist = 1
iter = 0

km = repeat(kgrid,1,num) # create grid to hold km
kn = repeat(transpose(kgrid), num, 1) # flip to hold kn
C = A .* km.^alpha .+ (1-delta) .* km .-kn
C[C .<=0] .=0
U = log.(C)


for j in 1:maxiter
iter = j
Vn = repeat(transpose(V), num,1)
RHS = U .+beta .* Vn
Vj = vec(maximum(RHS, dims=2))
Vj[1] = -100

n_optimal = vec(getindex.(argmax(RHS, dims=2),2))
dist = maximum(abs.(Vj .-V))
V = Vj
if dist <= tol
break
end
end
h = kgrid[n_optimal]

println("Converged in $iter iterations", " in ", round(time() - timer, digits =4))
return V,h
end

"""## Part 2"""

beta = 0.95
A = 1
alpha = 0.33
delta = 0.8
V1, h1 = VFI(beta, A, alpha, delta)

k = range(0,10, length = num)
kk = k[2:end]

# calculate consumptions from budget constr

consum = A .* k.^alpha .+(1-delta) .* k .- h1

b_an = alpha / (1-alpha * beta)
a_an = (log(A*(1-alpha*beta)) + (alpha*beta/(1-alpha*beta)) * log(A*alpha*beta)) / (1-beta)
V_an(x) = a_an + b_an * log(x)
h_an(x) = alpha * beta * A * x^alpha
c_an(x) = (1-alpha*beta) * A * x^alpha

pV = plot(kk, V1[2:end], label="Numerical V", lw=2, xlabel="k", ylabel="V(k)",
          title="Value function (δ = 1)")
plot!(pV, kk, V_an.(kk), label="Analytical V", lw=2, ls=:dash)

ph = plot(k, h1, label="Numerical h", lw=2, xlabel="k", ylabel="k'",
          title="Policy function (δ = 1)")
plot!(ph, k, h_an.(k), label="Analytical h", lw=2, ls=:dash)

pc = plot(k, consum, label="Numerical c", lw=2, xlabel="k", ylabel="c",
          title="Consumption (δ = 1)")
plot!(pc, k, c_an.(k), label="Analytical c", lw=2, ls=:dash)

plot(pV, ph, pc, layout=(3,1), size=(700, 900))

"""## Part 3"""

delta2 = 0.8
V2,h2 = VFI(0.95, 1, 0.33, 0.8)

consum2 = A .* k .^alpha .+ (1-0.8) .*k .-h2

qV = plot(kk, V1[2:end], label="δ = 1", lw=2, xlabel="k", title="Value function")
plot!(qV, kk, V2[2:end], label="δ = 0.8", lw=2)

qh = plot(k, h1, label="δ = 1", lw=2, xlabel="k", title="Policy function k'")
plot!(qh, k, h2, label="δ = 0.8", lw=2)
plot!(qh, k, k, label="45° line", ls=:dot, color=:gray)

qc = plot(k, consum, label="δ = 1", lw=2, xlabel="k", title="Consumption")
plot!(qc, k, consum2, label="δ = 0.8", lw=2)

plot(qV, qh, qc, layout=(3,1), size=(700, 900))

"""**AI Use Disclaimer**

I used AI primarily for problem 2. I was unsure how to go about the solution in julia and the difference between this type of solution and other search algorithms I have used in statistics.

First, I pseudocoded the solution. Then what parameters, the function, and the for loop until I got stuck. I then used AI to guide me on the solution, saw the errors and then corrected those and rewrote my function. It took a few iterations since I was a bit lost on the solution steps. I then used it to help create the graphs as I am unfamilar with the plots package in Julia.

Other code references I used:
Google Gemini: simple syntax questions, such as "What is difference between `LinRange` and `range`."

https://discourse.julialang.org/tnumber-of-values-in-an-array-above-a-threshold/2167/6

https://julia.quantecon.org/more_julia/optimization_solver_packages.html?highlight=value+function+iteration


"""